### ISSUE TITLE
Availability of ERA5 data from 1959

### ISSUE THREAD

**Issue by malininae** [eWaterCycle/era5cli#122]
Hi,

I used `era5cli` installed from conda-forge (v1.3.1). I've noticed that one can download only the data back to 1979, although the product is available from 1959. I manually tried changing the earliest year in https://github.com/eWaterCycle/era5cli/blob/main/era5cli/cli.py#L350 to 1959 and the request went through. Should I submit pull request changing it? 

Cheers!

**Comment by bvreede** [comment]
Hi @malininae, thanks for the issue! Indeed, the back extension with data <1979 is available now, but we have not yet updated this tool. If you are interested in contributing, this would be very welcome!

(Related: #115)

**Comment by malininae** [comment]
@bvreede Thanks, I'm happy to contribute! I tried to create a new branch, but got following mistake:

`remote: Permission to eWaterCycle/era5cli.git denied to malininae.
fatal: unable to access 'https://github.com/eWaterCycle/era5cli.git/': The requested URL returned error: 403`

Do I need some special permissions? Could you grant them to me?

**Comment by bvreede** [comment]
Hi @malininae thanks, that was fast!
You don't need to create a branch to make a pull request, not to worry. You can make a fork of the repository to your own account, and make your edits there where you have full permission, then make a pull request from the fork.

**Comment by bvreede** [comment]
I have opened a new branch on this repository: `back_extension_update`; could you make your pull request onto that branch? That would allow us to add further edits if necessary before merging it to main.

See screenshot below: when making the PR, instead of `base: main`, select `base: back_extension_update`.

<img width="976" alt="Screenshot 2022-09-29 at 06 33 12" src="https://user-images.githubusercontent.com/5747405/192939576-da05c01e-e9e1-4a3b-8849-bab3a5ecf466.png">

**Comment by bvreede** [comment]
Thanks so much for the PR @malininae! I'll get to it ASAP :)
